name: Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B clean test

    - name: Notify on Telegram
      if: ${{ always() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ job.status == 'success' && 'Все ок' || 'Тесты не пройдены. Пожалуйста, проверьте результаты.' }}

    - name: Disable email notifications
      run: git config --global user.email "actions@github.com"
